name: Android CI

# when ci should run
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ 2. Set Up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ✅ 3. Cache Gradle (Improves speed)
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # ✅ 4. Make Gradle Executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # ✅ 5. Run Build
      - name: Build Project
        run: ./gradlew assembleDebug --stacktrace

      # ✅ 6. Run Android Lint
      - name: Run Android Lint
        run: ./gradlew lintDebug

      # 7. Run Detekt (Only :domain JVM module)
      #- name: Run Detekt Checks
      # run: ./gradlew detekt

      # 8. Build Signed Release APK & AAB
      - name: Build Signed Release APK & AAB
        run: ./gradlew assembleRelease bundleRelease -stacktrace

      # 9. Show output structure (IMPORTANT)
      - name: List Build Outputs
        run: ls -R app/build/outputs/

      # 10. Upload APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

      # 11. Upload AAB
      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/app-release.aab


            # ✅ 6. Run Unit Tests
            #- name: Run Unit Tests
            #  run: ./gradlew testDebugUnitTest

            # ✅ 8. Upload Debug APK
          #- name: Upload Debug APK
          # uses: actions/upload-artifact@v4
          #with:
          #  name: debug-apk
          # path: app/build/outputs/apk/debug/app-debug.apk
